name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
          java-package: 'jdk'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build with Maven
        run: |
          cd ~/Bureau/actions-runner/_work/SpringApp/SpringApp/spring-boot-hello-world-main
          mvn clean install

      - name: Run Spring Boot application
        run: |
          cd ~/Bureau/actions-runner/_work/SpringApp/SpringApp/spring-boot-hello-world-main
          nohup mvn spring-boot:run &

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Start MySQL and phpMyAdmin
        run: |
          # Pull MySQL and phpMyAdmin images
          sudo docker pull mysql:5.7
          sudo docker pull phpmyadmin/phpmyadmin

          # Run MySQL container
          sudo docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7

          # Run phpMyAdmin container
          sudo docker run --name phpmyadmin-container --link mysql-container:db -p 8081:80 -d phpmyadmin/phpmyadmin
