name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '1.8'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '1.8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Spring Boot application
        run: mvn spring-boot:run
        env:
          SPRING_PROFILES_ACTIVE: prod
