name: Deploy Spring Boot Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn clean package

    - name: Run Spring Boot Application
      run: |
        echo "Starting Spring Boot application"
        java -jar target/helloworld-0.0.1-SNAPSHOT.jar &
        echo $! > app.pid
